CREATE TRIGGER trg_after_update_classes
AFTER UPDATE ON Classes
BEGIN
INSERT INTO Classes_Log(ClassesLog_DateTime,
                            ClassesLog_Type,
                            ClassesLog_ClassId,
                            ClassesLog_ClassComponent,
                            ClassesLog_ClassSection,
                            ClassesLog_ClassMtgStart,
                            ClassesLog_ClassMtgEnd,
                            ClassesLog_ClassMon,
                            ClassesLog_ClassTues,
                            ClassesLog_ClassWed,
                            ClassesLog_ClassThurs,
                            ClassesLog_ClassFri,
                            ClassesLog_ClassFacilID)
    values(datetime('now'),
           'updated_OLD_values',
           OLD.ClassId,
           OLD.ClassComponent,
           OLD.ClassSection,
           OLD.ClassMtgStart,
           OLD.ClassMtgEnd,
           OLD.ClassMon,
           OLD.ClassTues,
           OLD.ClassWed,
           OLD.ClassThurs,
           OLD.ClassFri,
           OLD.ClassFacilID) ;
    INSERT INTO Classes_Log(ClassesLog_DateTime,
                            ClassesLog_Type,
                            ClassesLog_ClassId,
                            ClassesLog_ClassComponent,
                            ClassesLog_ClassSection,
                            ClassesLog_ClassMtgStart,
                            ClassesLog_ClassMtgEnd,
                            ClassesLog_ClassMon,
                            ClassesLog_ClassTues,
                            ClassesLog_ClassWed,
                            ClassesLog_ClassThurs,
                            ClassesLog_ClassFri,
                            ClassesLog_ClassFacilID)
    values(datetime('now'),
           'updated_NEW_values',
           NEW.ClassId,
           NEW.ClassComponent,
           NEW.ClassSection,
           NEW.ClassMtgStart,
           NEW.ClassMtgEnd,
           NEW.ClassMon,
           NEW.ClassTues,
           NEW.ClassWed,
           NEW.ClassThurs,
           NEW.ClassFri,
           NEW.ClassFacilID) ;
END ;